name: Build and Publish docker image to ghcr

on:
  release:
    types: [created]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: planka
          archs: amd64, arm/v7, arm64
          tags: ${{ github.event.release.tag_name }} latest
          containerfiles: |
            ./Dockerfile
      - name: Push to registry
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }} latest
          registry: ghcr.io/ThelonKarrde
          username: ThelonKarrde
          password: ${{ secrets.GITHUB_TOKEN }}
